void setup(void);
void init(void);
void clear(void);
void sendBit(int);
void sendWord(short);
void sendChars(char, char);
void lightAll(void);
void display(int);
void delay(int);
void add_char(int);
void display_frame();
void scroll_display();